export const CHANGE_ACTIVE = 'CHANGE_ACTIVE';
export const UPDATE_POPULATIONS = 'UPDATE_POPULATIONS';
export const UPDATE_LOCAL_POP = 'UPDATE_LOCAL_POP';
export const ADD_TO_LOCAL_POP = 'ADD_TO_LOCAL_POP';